version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 32.3.1
    - 32.3.2
  - dependency-name: gulp-replace
    versions:
    - 1.1.0
    - 1.1.1
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
    - 3.4.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 10.0.1
    - 9.2.4
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: postcss-import
    versions:
    - 14.0.0
    - 14.0.1
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
    - 10.2.5
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: prettier
    versions:
    - 2.2.1
